include:
  - path: ./infra/docker-compose.yml

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    env_file: .env.docker
    depends_on:
      - db
      - redis
  matchmaking:
    build:
      context: .
      dockerfile: ./apps/matchmaking/Dockerfile
    env_file: .env.docker
    environment:
      GAME_SERVER_URL: http://game-server:3002
      GAME_SERVER_PUBLIC_URL: http://localhost:3002
    depends_on:
      - redis
      - game-server
  game-server:
    build:
      context: .
      dockerfile: ./apps/game-server/Dockerfile
    ports:
      - "3002:3002"
    env_file: .env.docker
    environment:
      GAME_SERVER_PORT: 3002
    depends_on:
      - db
