include:
  - path: ./infra/docker-compose.yml

services:
  api:
    build: ./apps/api
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
  matchmaking:
    build:
      context: .
      dockerfile: ./apps/matchmaking/Dockerfile
    env_file: .env
    depends_on:
      - redis
